---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: auth-app-secrets
  namespace: default
spec:
  encryptedData:
    ACCESS_TOKEN_SECRET: AgBrgX35AI9EnmCdsvldw90NaSxccYOP8lD4izW+JLwnaWQbKiySAaFo8eHXDe07qSJaCZlo60ILZF0q3USMGcTmkxK+JSJ/m43iOxnJrJPVd27hT13Q10q9Etc13EV8Y9MvD57Pf1CV93CaiNSsj6lgljzZ/uGXDU2DRKBRsiQ+/Sxm9cr8j/eBgqke7IdbnXPci7FmlkHZn2LKz/1DWG5mVpNyyKJeu9uPglUaeNWttWoxvpPiLZjmKY3+SDEng1TPMDzWAay0h02u5ibSLw6ujucfU79FKovJOpZxbchkdVC8Cc73eITFu96znX9A3sO3u2NImWGcZgL6kquWURSeReCKIUGQ63L7cCE9YDGdH3efVneKJq+aK/PUXq/OrAJXJRzUnd9quvD0D5WoKnv7PYz0LmDydYmDYBzwEhDkA2fPyeasiDQBNipr+2jVZSMSdHlAgibsl0AYkgA2HwrKn4i9DHePKrpjDUy99wJgarqBoDnQYllfAJ4jMUwjDtPMPfuN0l+WI/VaNPFSGm9O69lptlrBbIUAv2it+g0S057nC5awI3ua3TtbV6yN3URHYg+sEwNZsFF37D185NUY6Xqmttc1sdBDH3c92hYtE8ghKEHHFFIWUFA9IOE9uleA626KivRLJ6ei8b5NtaXBUwALVEcgeizBLXB91zh9xIosFDCVPqz8QnyybCQn6ZEIGXYnXlmiyziuGPKXp69S43940CBC7+NQiEpnr5AQjRbsdTM20s9hdzKv2pDVBqc/vqN+82r46SZBgA7T63Fq
    REFRESH_TOKEN_SECRET: AgAjFYC0ZvUVy02ahBrrgVxgoCLLOSgN6DPufwVCgAN4ptVoSCA7iH6lt4OB5SiWpI+pIuiw64rROKETz9HiAC+RsWh8o3Ctj/2Lfzpw/VMFkCU/WH923TZZxIe7HFyxhdKmjeJd9ynlxFNklzU/iU6r5mYiLE6Y59oY8poJPQjxZ+VQ4dOVTHFA6f6I6YwipLlzZ2PSufgZCXjpNDnVgLInta9dNEufOQwYFETaXhAlOpySa4c7h33MTd3AAqv0/OCExr3zj2RuNdMBHiN1hLUFKfAtmQy4/A8epCjLnGZyrV5HZd5urzaBmqwZca9yw2p485uk18UdmqNRy2EWkqy8bG8gkFUiUo+OG66oX20URRe7p7llTpIUat5TuLLurPgSMhE7qDuw5u51JI8hR3qlWnyFo2PW+Q055NmX3N/QubceQeuguWvj0lHgY8fPyCv+zRDU5ZInnyHJ6GnAVJiGRnQU0LjAK50SWqT8bEr65G25SsusIZAMuBmhg4x+cZEd1ZE6tblKQEXs0pR9ein3vrwxaogXvH9J0jR4hbLTAEPFm+zpE1D6CodrungbzKkDhcTLebfPr/b+Icnx/mYDNWbftYljHcZtYgkDDa0a92+mle51hcIcty6LZUMvAHHWDC+DZzMw4+ehCPcE+kdHxlLMgSJIk1MImMDmNVQ19QOB3lrQKCZ92GccZXlJSd9NUNW3Tpi2MABzF5QQv60o4CAJ/B3ur/cRQH15ht7Jm9DEP4S7t4GebTFi3bXpKkMOFjMfcaDTf/SjPLx2CFcw
  template:
    metadata:
      name: auth-app-secrets
      namespace: default
    type: Opaque
