---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgC64Uh5OyMdXlvkiOSMGAHpSYQTLcFq9A+d2zvFCmTZ274GT3eq1Mm2LnDkPVf6Gh2BINAEcc+DBBPZHd7mpD3TFSJ6VgzLSsji34ht+cxA1eGMH0nabN6kKMoAm4ALPUwCJldLOnuz5Zk5TCxMx0Ik5mmuOPTgQnmXgdmIXHDi73Nm6/+Pmz/pRqy1fV8cpH6Pcs0fZyzJA7Xuzh8sIbgm/VQ8MMCNn7Jv/oncrrZsAIzRlYtNqpD3BR6/MLjTEDVSX+UEiWQv7O7P35WajswaUNnbcA6+Wzbf/eN/4eYXEcDPBRR3JLH8cpxSqXVdLdn7eb9hfgPy4zYThAd1YwRr5f5Fi6cOzOrxxV6uTS/+W6RZDjLlEKL+48ojM413qZRainZFyESL+UQ9cyzURP+JFetmpdgcMkpPA8TskGizFmJbgU7BykPUwLejSkpN2QO+V/483q6neW8nAeRsnQ9mFwbk4P/kPHFQgo2HRaMATTe/uah5z5MYJTHyifMKhvNSrouxUihHSaQ0DBSHzKw9ln1A4ZqIksAkyZedenA0u2FQqxSPpyg6aH1UzgSN6kBNUoulpzVGiJ5kjpC9OId6mpfzT4aPTy7lhCQaBI4Dpp9ckuGs5yq27qTvsysHS6LbeYkqAHMwsL61ZUEd5etQAIvmad4WIcTci8NDmF8qjXKfiLz3kVWX0wZeqqtZERBuVM0vTMdN9xmCk6UPGiW9hS3C+BwJJvfmIB9aVv3dAg==
    admin-user: AgBmQLEiwq4TybAWJ4QkuwlLpeQMS5NwS13tnNo7FcAHKUYaVrhgZc85q7NEsZfjiOwR6nLMsr/sdoT0wSeaXZrJLY/gte1UHbtyrrTjzwUnzrq0N3GAU3X79dH5+Y8IzRutMoSwbMivHyRPyLg8Vm0n1xPoXSqeZsk1RSeW8aAE2ibz5I+wnZWHgwKcDBq8aqKGCGLI6RlZUKbJjQ37VgwZfiDYfAlgoKJbZXO7xOJB1iLMS9JB3YwOZm77x8UQbDAw/5RaNMCSHJclZRYWb8ScVjF992npYESW9jHZPqXd+EsGKzVNR4SXlY4qG3ebw7o15WTnim7aMU44XKkldSPizO6/oLWgAAy3hf3gdtnM9xzXPdeRKQhgWEpHAS+43zTJRIvC/EGDuKfIJMX2h/oD9Tk53LQg/Yl3XBu40krSfQXpbfvsymceqyH6hN+HbTVHP4qFjSJTqdGJf8LIi+gsx05HTNh1MJXVwXuEn+V0ZgzN9pplxIImDO6nwerQ94dN03iGkaAlE1hyZ0hRFeK3GaZxxOI5CbAxa7V3dqMlQfRNG5X3nZI1PvYUjYxldTu65vAXunM3wRzllLGTJWFCWbWSo+PqRIEbKuAcjY2+KIgX79+kfTWB+nLFe6Cc3hNMtn07q4pX3fAR20+onpNG1ufesWU9dgSf+mwG0UZP6QghhUlJwYsmXu5G8KRp2lH5LfRtnA==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
