---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-oidc
  namespace: monitoring
spec:
  encryptedData:
    client_secret: AgA1F7DgiKjq6CNd1Qwlz6sQHO1b867XyWQ4bdSrFQpZeATmMU+yGrK58QGVYVdtK+tQ+hJeDRE/CuDmGOBAzmZ3bcOwOCCgCozCar15PnXvzCWbAam8OGOVGrIhbi6H83Q51obMQxp88eHluxw43uDkkxpcQ9hYPZRdn4rgC2X8NUpu9IRgNHx2jgjLr3aB/vsgGM3+BaBEfz0xsjvxLFK8RZ+6ypwJDyHeUFp8hz3jhlGuYw+7i2pFwW28JwRrpwWFsVHs8SIXQK140PgB2DkL0SC+WH71pJhncBFYQVR4yf236NbA8XnHgZDHEFRRcep1FCKewpqqNmZgPj9qHPNlW/o1qA+6b+dUyTQtWpn8z4pFlBGQhMRBUAMhNFid/gnHlMAhkux+pzn715Udfylnq+4+YPetvX4uLEoA+gxPVcA38PViOeFgZzDLbD79p/BykvpDZe/y7RRq0FVtr+koWqr/dKHrEk/oyd2lPneYXFnWxHmvH36gAtQk2fp8DJkSXttLQ5bzX7jweNqE7V15jhMWj0317aDv+R+STHAStf2leNSJxpcHedQ+9T8ONg/JDAjiKTSJZWIGBmdw26lAKzyqUiKMDX7/vJJwbzvDNF0t0vKcmOvyXC61fXGS5rAUPYCA9I0b912eBtHCWDALSEtRKUPF3tVtz41Wa9rqC4GVNBIYQYKUXvKkc/1lktAiJZP7wXFgVtk3xUmia+tGhJn3/MaBnh8PdUuArdJWAjA=
  template:
    metadata:
      name: grafana-oidc
      namespace: monitoring
