---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-oidc
  namespace: monitoring
spec:
  encryptedData:
    client_secret: AgC6OB0ww2FSnYBDUjY6ZpiLNCDTkk0tXL70P9xbFrKMi4O/rdqvqzfAQstwQ3pOiVpSCA4ASMGwij0wXxIcA0vkg8qx+raiV3kVJTIv+jhvkLZUOrLNda+6mop6dv67EKTrm5hjGHLYwTnJZKVUh3AdRytHsmnKIMJFVGXxJL7I2rUf23XNfac6n5aB3v+Pw/Z5LC5p6ADCGl4JX1wQInvJpuLnH5tHTVKhW3hawDOiCoPecdb/mdnFSvh4KsPL3PO7hdcPsrov8M4EtXB7NRXTJ+f9TlSlP0aaDW/wma38R4IuV2iKrLOpx6yejL1RwjiZPGFBg4F3Wouva6PlCbxgEnhbMDEZ0U/00/tTd1LIrAF4bz+l2vu93UjcNvrig1LA0Fj/c7noYRSmBnnsSyHGKIpZkTDPRw0Io8TWUj8uv9WzXtKyXw3coT9cB3/IXGG+x3vurn+BLmrxNwKAEZJ+wo0TMSv5UOtAMXP210RRI9tGj//Vf9ieuMUyyG+h57jzw7mpvvoDwqJLHptRfW5jtRP6BvHThC7Ky/WJgW90krZlGXrmM78YXV1KRwIjCaAWoJ8eEtJN1Qkt88pVBFlGkiwZY/nsXtTcEWpE/BzxSd8vpLLzPMdeXB4y1m2vVECY9j34CCQZdp2cRynOLpEdvGT2YdCwqUUPoXl6DE8bvsNC3dyd6GAayNRy/tLHPgzf2uc1mnrsdY1XOtmuc8PNfod4HiEtrS0emj1cy7rrJw==
  template:
    metadata:
      name: grafana-oidc
      namespace: monitoring
