---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-admin
  namespace: keycloak
spec:
  encryptedData:
    password: AgCR2gSQdqyHoXbkCrCDKArbes6u5T7vyPuoPYwsEZj5R7uKW3IKZIzPbVt9K5s1hrbbmGacBfu1kNEwufD3X/g3ibLjKZZYozmi8WEog1zdR4A/0VN1dENAZkwiAEzoymI+RjRCpcjp/hRcyEsnFm8SKkBzQcIwi8Bea1LLTlq2gGF9fb6z431JVus7MBpBYyFEgeKIHF4+tUActk8LUhJKnpehJnUAyVwQMBQRVjxP4XIL46d7l8J+SqoGPisc3X2ULLSruf4P3RpMvBgS98/iToiWf5cfp0Omx5+sOe6WZX92+1+Z5+dIg2VBoNoTM1HDVjCxVz7briKH//IJC9lkN4OSp5M2aKcVLF6LzA1YAQdMu4uu7U+4oDYp7pB6NFF9pHEswbvrQJwd+ViGXEXNbiZ25B3qvZoK1syCI25zzGsTqqJo4b3Cs919s19pHJ3fchLoCqge8HugfS/cUdKoWOC3WK1BmWQA7DcBUSfR3UEJfBgIDABQDT7fgd5JSKWOJgjmkQrVWh8+ImNqkfIFSTu5YmWTF2KCIPJ9tQfmmY3e4NEstGdOTkCunj6SRELnHvSgO8/+NOXLyMNjC93Sub39x+Sw6CbA3zZB6M0tn+vI+iRjhvDuftxBVOp2DfMxim6WdHlQyNlu+0sMHVyGdfW2KaQ+lgCaGu2eG5gmzxtjqwTjIBjCwcF8h2fU0k86l5q1B1jTei0f7hj5s+Uq2zn8JHY2FiJzhijw8uDf9A==
    username: AgACJxfrXnJruindXlTMyadvrR7RcxVTY2plzmg9wuTTF0aMVSy9uwD6ylOEJ9vNjO+RnhRvfHJvEpYpia3z3RMnpAUQpWCD9RiD3uDN/MvAIPsoh4BzsTChiS+fm6fySA5un58WM8aK+AW5iadaaghjcO55X7tv/0f5y8BcxIDKHtmyVQeO/euVc/Pr1fBv/QaGHYgtz1VlB+FrmX+LY0Hs0LteUtj4hW+XboS9zRgXoY2MoZGHrMVK6uiaYOGCxFhNVaFTvo0vJLaXlU+2Rs7QSbguvaa6vQOKQYQDE/6M09iiIvlgCmzK/m6lqsqIltqwOTyC4+qbPlYwjwkZPM6Pc1o6bpvutK9MNi0SUO2pCrXox97jRzHGzBB0s0kseWi4jSLFKcKdWF16jpAkHxf7N3c19q1JwxVDdNBD0SpSqE+n+heMbeYppZY1VIB1YbvZh62+EmprhSeE7iY77iCDTupNW7URWcXZ6eBu6jSTbRdIiSIENlk3KCY/d3tocGwBGYMqOWaLGPiS7frbyeEZbrrCIkBolEWJ+oWQ8eqoHursMZRr4T7hIK42Y+CStF60nhfCquXLusHJc1r6UwttZ12OkAVwFldZedhDAEjHBJttIIHq82H2KSasFWk55ywZx0hq4BupkPom+xcHhdl8YFT6TgiRFO4oZDhxdsid/iFD1Q6SxPSQ+Vdh+qjwMf8FMK2gLg==
  template:
    metadata:
      name: keycloak-admin
      namespace: keycloak
