---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-db
  namespace: keycloak
spec:
  encryptedData:
    password: AgA+wvo4eWmRjbvHzomEb4NvZKNrJiZL1xDIaohRnQmYjaLUzJQcdfCZx1D9hFkCy3bnYO+PBwecIfexwd9A6AFb3QI8CiCqvf6v5ZJzpR5RrGbJi5IL/m8BfNo9ZjhzCxZ9dFIsrqqHVXGE8IIDORVgzveSzOlQjhnR0igjMI7Gtkv7vU2ydB1Y54EjNK2GxhUd3s6YRQdXJpwBJvi9fvS7QgZ6YrPhTZR4hI0GyVjZI/j1Jis0sHRZ1gWbjFKq856L82HPXl0M3CY56rnpOe8Fpi10lfuJXOtbEBPeEt80efk7z1tg2SDKRkYEaxBdSHtMaDL76zZdMq2p8Ij6EkN77F8fM/me+lFLAJKDum0owggOdtaI+jeOkGv6hwodPglI8Ur69xqxiH96CcuigCwc6zB3VxtRnwxVf1snW5Vbt/3aDgw+yWIYm5pOB068sVwKATDk+T+N2KvxdwBpWLogPuWAf0bqETj0MduHqT0/jBWVejMm3/GweKq3R7d0jOilSTSvRZ3lP0kmZd198Dqibfbka+UZKShAgDfWYmVNB2pa0d8agKsoVGFtrd5dZtorpBcgkJkUqdiOF34mhHSGbah01NhnuFifnfjq1UDf2Ezd5YivaZvB/DgCZ4jXwXaWdRIMmQpuqbbqAKbHBJXDxlr67Pp5l8Q0zOh/LVDvsuLDpG7TNA5zF3+P/2uv9gPmcB+1dV07sEhQxLuPo/DHUHwD9ObYs8W76AcoSrqWFQ==
    username: AgB91yLs3FlGokHdt87NEPcUrrbNLuFYwQg4dHUuCNY6Ah1VtAs/nuuiX6KRtUWK8v3EwIKb8jiPUbNj6vhz8aSxEXvl6hS6hj821GtYU6pbApftlDVJ8TRhIlslgSWFLctY2d2k+b70SE/0E7CxgNfUnV+s2Miv/2yc79oNPomRHmDZxLRPkZZ6h02rXbEDUDL/ZoDFTJnu9IjugdkcyPNfsYzgzaND7sPaTaZ8xHmOtnfICjISqeZMUjWtrOAubyCHtII6epiRf0J57MetHeaJsjTgOPGE6uxmpAYAfjVskPt5ZFIl6ny72I9Fv997Z3Sd1uwZ/Qy3Bi2lFpxmVT3NYeswjue0bErA+G6093gm9w3ftftxyfiFdQWNbm92CsEUqn2Q8V0X3kfys4x/fmdKP7O7av/c98yg+WtpI4H0nb0FxQod0se03n5e+cVBNh3qhiA8hURri6y3VvB6AYrwBoePV6qNvypIqZupvsy2ABcykUaVzmwBNtf1VcfJyUOV0WWs0cIhGzvbfpnOv+WinOnIIsfD8Ox9tLLkeaqeUbqNsqvbGWcMyYAmJw5hzi6jmzONjMEgwZS63jI4t00Hn09Vv2NEaDtQI7brcn8aX1HIwEnvkbbRAUyBRdw+1jS8NA8fClWIDMZvJdl/FZlLpzZGTwFXD48OfLVoNNLhYba3x9Ayx0v6Yu+TcHEL6pJDxN0YhUGBcg==
  template:
    metadata:
      name: keycloak-db
      namespace: keycloak
