apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ../../base
  - ingress.yaml
  - ingress-tailscale.yaml
patches:
  - target: { kind: Deployment, name: auth-app }
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: CLIENT_URL
          value: https://auth-app.tailf46ba0.ts.net
