---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgCIucGan+Dq7LvTU1xWiOt76oB/YvK8rDCtyVETrxaCb3FgZylvY6cbsGITdZEL1OcFLxDBO78w+wq4D4t/bPW7r5AaLQk03nTfl94peVz9mUjtOainGEDOnzF8Uj2aRYmpGFcmatLbfKeSrP1xf/OKuTnmyf0HajqDiIUtRnJWpby7+FNWidCuvxdZ0hX+wa6t441No1BMa8p5AB4atDTIHazMi/9xouA2csGr7mjmpUBNTa9R6UzDX06+pfPEYgzlkZtHSs1K3OIAgySfYV1ZrQhiwjZux8Wob5czWAeenrO4xqNfE0Ooxh76O8esIm1q7Ih5tMzkMHoIg60PuDZX+VZALLL0XSbWL/YzaujVyxzLTpb2Yp3cgqNhevmxVzUSet0ZZ6FR9gg595srfRy+U82taShdt9KJpGrN21eMxKD5dhv2iXEkQTOrTcnWfh83OIIvNBzQ5CIsRgqPCNii9qj5n0eGqYAlNCPugprlVs3NcYrjzV5CLr5PzlzIu+MPPtiuQLkLJBfPjxYTX84/7cIX7AzjyVSKgMeditdDBOoPHIhNb9+H3/DDb4Fqn1V+9919XA4qv3H37ZbOcWytwm/k371E1/6Ul17hDL1bW9+uD6WtajQ39+i0Hpp1bGcKzLGgAoojJICGb7e3xy0KSECTrpqk/+DWZYLseVMgO9RCnmaHytFTS2gOfLkH1zJ8YyH6VXsInXUiCHpecOWQew==
    client_secret: AgAcHOgAbctr8+R2wUpuG9ICjOni5PYeKNdvJXSjfn9wWXI/c4AIJYsv8pceacFeiTy9ftm/Q/pbFac1l5NI7MMU/sAzWBuvb7HMh/dJGmrB4G/Xo9KPhCABGFIUztwWV4L7f++GoZQh0MEfebpxi4OSs508hRkfkFe0ieasKjemvbbWLo7FMrNa/iYRyfEcIB2m13HDIYcJ1LxQkSrrKDSww/repRyeLIhvfF2GaWDsRK5BWYlFg/JLKUIu/VyqOkTSXTcNfcMjk72Q3/NdgdGW0pLy/LOKj9NifM/hKoH3CbRgCKmyCEt/4fDYMlM41IF6JVO1i1wX0CAKZrMutQ1JQoKZEYUkWHVVznFbAySp5TZ97JCeLEO1r9cjYvmr0LC4qq5MzaT+clKnW5GOEjOCYfusGq8lbSM7iMPvxRHjNWJ3onDrm7sqsdV7EWT6Qd7w/dVsW0q6GHgBgH4eH9STckfHW/VD0ZePTWYsTatY5hvNeNm6ds0m75ALdA9IKECPK/HOEoXQjXw67sQ1SAtUp+lcSizS8nADWCrr5XjEcRhCPS5clXkCX/Y51HMY2C4djVhfs0iFYwSfvL6fKnGMd6DlWyIoS7iz46Y+wzAu1OZgF5XgzuhZZhj6QL2n1oEZIsOD/3J7D0IeKnEAEP+nHGpIstOjxuaxEyQ4nrHpOWAO7Z2vkTv0pahSBsMVzuwG6a4sKhPtyg4jRLdkop046qiXqWmtql0dlQYvX+Ha35dZbvP60YslWW543nZmNimzWmVypPoXQolp1Evo8Is=
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale
    type: Opaque
