# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: auth-app
  namespace: default
  labels: { app: auth-app }
spec:
  selector: { app: auth-app }
  ports:
    - { name: http, port: 80, targetPort: 3000 }
    - { name: metrics, port: 9464, targetPort: metrics }
