apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/HamZeus95/platform
    path: manifests/auth-app/overlays/dev
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true]
