---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: auth-app-secrets
  namespace: default
spec:
  encryptedData:
    ACCESS_TOKEN_SECRET: AgBlW6XXlPLWe7sLfOJ843wXulhMGX5fGBpr0ORIP2IqyS+gaRgSXhdoUu8idTM3ZfrjsMgf8oOl0Skca6cJqwwKG4X2LgTQPjnoSgW4ol/LSDU4qLQrA5hj/AURlCe2jOiDF3PpEP2W8pOVa9zvucBS/e5mu8ra65QYqWcHlRudcO1K7KZHuPkftXzg5z2CPKQgYsLtrJwHezeb0X4YHaoz9NAgPhVATCT+m6qWltnUdEEugnGnhYgY3uEPJJSdDEs33IzgPDTj/cqXkrcdsqnzdiQ1kXLa0yFnUDymJon0XIGcHKuk2GvYfGk2eOAFTCIwAX1Vus+74MzS/h/JYZ52DLHLYFYESP+0nX21XgTmEV5HZSCVNqCX4a4a1e8FVC02B8sacDzYDrucN0WTSmk5MuQOL9ES8b+Hv6OQwso5Rk7tQ4dwBQsqgIrcAsXuJwY6J4UGeaAvzTUiLErOqWido8iAY1uJ/zt0A3lU4qcLc5vqUVHwTQaKsGISKwpdT1xOwvwFErSFSXvAF1vlghP+pAqG51UHU2ApzrneuishkFwbIzkcTI+AdbBoDq5Q/EW/v4VNvJbHNKoWZrPWyIJlgo2kx/lkD0qqz4CCp3ntY+RVd7RE+CZ6YH1bxzqpvlwVEnkqvE2PpV4lbJdrxHxIGb0Bjxhis+x0UbOoAIqLvP8w9H/Dgk05bFhLoa6NSVw/XmyBx/JNBe+bVPYrhECMJDHerOY5jzliMD07grSniTITbtVUgiH7+nvZB9rEW4JZi2+cW5byAfEQKhxgbHOb
    REFRESH_TOKEN_SECRET: AgCe5Hxy5KuWqgD7BDY5fCWTRuIczOP66EG2wNEWDclwl9t+xUh9JeiNn4a+edZVY6TQS1gTmHiMU5PiT2GTVudAPaN8KDalnN3V7ZqICSiSDuJVaOu9LuFbmYjS1UxMFqWIMSaJ4xR7xg96ppR1vkZbJvoOJvXQwFRZE5XeO7JTYrmsybcrP/nsneukhmFyrpEdoHGMPqovvAMYDxi9GO7Dyer/RVlNKIeBYu2j8M2RqfkOF+O67ttdPDKt17OhefzQXDRRTYr7Tzg04SNc4cCtyjl9OHR3hrXyGZ6J6OiyRrTelpedb3OY4ZldkREQ9GhjEJT2oieTdSnueW/gWQgEwIDz4C9PMKGY6L0cde4yrX+5xQWBnHCy4tOvv7fdjjX23qWrz9QWaabtd+ny34WrHWoYWhm2dpCbNwu0ul2xgoh1FvTStF3K9SgqQCONwH65gzdskc6gphXfisT+9wZ0cT9v2Krz7YLCJfDmsM6No8C0g0LF100zAVRr9nhx4U+W9qId5rHSjbZQJmlaH3+cIr0utis+b6JUmtHCy5EycpoZQR9aXYRxb/OqgQNd48S/6FyW7bIJQwtkT6D+c+LHhxxG/dbSNyvvvhHvmecW7q0CJp/teCxgihFQzyEJG3WkR8RqrWPg4EhuU/Sp+CHkmn2jYt2ht0sIRgFhqxSAlrrqYrp5RjY9GXJOX16Z75QdKO41aHHmro47WzYxtjm2pC11H5TfB7vOg4npL6MM2YPHG0iKprTqzHJeTZz/T519XwZWWEL3uRGCtybT54bN
  template:
    metadata:
      name: auth-app-secrets
      namespace: default
    type: Opaque
